# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "osbuild"
  config.vm.provider "libvirt" do |v|
      v.memory = '8144'
      v.cpus = 2
      v.storage :file => 'disk1.img', :size => '20G'
      v.storage :file => 'disk2.img', :size => '40G'

  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update || true
    sudo apt-get install -y python3 python3-pip || true
    sudo apt-get install -y mmdebstrap dosfstools systemd-container ostree \
                            systemd-boot python3-yaml python3-rich python3-stevedore \
                            python3-cerberus python3-systemd python3-click python3-gi \
                            debos rsync gir1.2-ostree-1.0 git
  SHELL
  config.vm.provision "ansible" do |ansible|
   ansible.playbook = "playbook.yml"
 end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
